name: 'üê≥ Base'
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - 'dockerfiles/base/*.Dockerfile'
      - 'dockerfiles/base/*.hcl'
      - '.github/workflows/base.yml'
  pull_request:
    paths:
      - 'dockerfiles/base/*.Dockerfile'
      - 'dockerfiles/base/*.hcl'
      - '.github/workflows/base.yml'
  schedule:
    - cron: '0 0 * * 1'
jobs:
  base:
    strategy:
      fail-fast: false
      matrix:
        group:
          - jvm        # jvm-community ‚Üí jvm ‚Üí python-community ‚Üí python
          - dotnet     # dotnet-community ‚Üí dotnet
          - clang      # clang 20, 21 (Trixie)
          - clang-16   # clang 16 (Bookworm)
          - clang-17   # clang 17 (Bookworm)
          - clang-18   # clang 18 (Bookworm)
          - clang-19   # clang 19 (Bookworm)
          - go         # standalone
          - js         # standalone
          - php        # standalone
          - rust       # standalone
          - ruby       # ruby 3.2, 3.3, 3.4
    runs-on: ubuntu-latest
    steps:
      - name: Clean up
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /opt/ghc
          sudo rm -rf "/usr/local/share/boost"
          sudo rm -rf "$AGENT_TOOLSDIRECTORY"
      - name: Checkout
        uses: actions/checkout@v6
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: registry.jetbrains.team
          username: ${{ secrets.SPACE_USERNAME }}
          password: ${{ secrets.SPACE_PASSWORD }}
      - uses: docker/login-action@v3
        with:
          registry: dhi.io
          username: ${{ secrets.DHI_USERNAME }}
          password: ${{ secrets.DHI_PASSWORD }}
      - name: Build and push
        uses: docker/bake-action@v6
        with:
          push: ${{ github.ref == 'refs/heads/main' }}
          workdir: dockerfiles/base
          source: .
          targets: ${{ matrix.group }}
          set: |
            *.cache-from=type=gha,scope=provenance
            *.cache-to=type=gha,scope=provenance,mode=max
