name: 'nightly'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 3 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v3
        with:
          go-version: 1.19
      - uses: goreleaser/goreleaser-action@v4
        with:
          distribution: goreleaser
          version: latest
          args: --snapshot --rm-dist --debug
      - uses: actions/upload-artifact@v3
        with:
          name: qodana_darwin_arm64.tar.gz
          path: dist/qodana_darwin_arm64.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: qodana_darwin_amd64.tar.gz
          path: dist/qodana_darwin_x86_64.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: qodana_linux_arm64.tar.gz
          path: dist/qodana_linux_arm64.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: qodana_linux_amd64.tar.gz
          path: dist/qodana_linux_x86_64.tar.gz
      - uses: actions/upload-artifact@v3
        with:
          name: qodana_windows_arm64.zip
          path: dist/qodana_windows_arm64.zip
      - uses: actions/upload-artifact@v3
        with:
          name: qodana_windows_amd64.zip
          path: dist/qodana_windows_x86_64.zip
      - uses: actions/upload-artifact@v3
        with:
          name: checksums.txt
          path: dist/checksums.txt